### PR TITLE
Fixes and update translation to Russian. To dev branch: /help/object/po/po.ru

### PR DESCRIPTION
**Pull request by X64E**
Result:
objfix

### CODE REVIEW

**Comment by X64E** [comment]
How to recheck pull request?

**Comment by X64E** [comment]
Is possibe to remove first check???

**Comment by MrSimbax** [comment]
Hi, I don't know what's going on with the check, but your commits are still based on your fork's master branch. I recommended to create one branch per pull request. The branches should all be based on the original dev branch. You can move your existing commits to the new branches, for example with git cherry-pick.

Also, in this case, I'd just create *one* branch from dev in the fork and push all commits there for *one* big pull request, since your PRs so far are all translation updates for the same language so they're related enough IMHO to be in one PR. No need to create separate PRs for each file, there can be multiple commits in one PR.

**Comment by X64E** [comment]
H'm im move commits to dev branch. And second check is passed ok. All will be ok.

I decided that the changes required verification, so I decided not to make one big Pull Request. The second reason is that I am translating and checking step by step. Who can do a Review? How long i will have to wait this?

**Comment by MrSimbax** [comment]
> Who can do a Review?

I don't know. Nobody in the team knows Russian well. Only some basic technical checks and verification with Google Translate is possible for us. We will trust reviews from external contributors though, especially more than one.

> How long i will have to wait this?

I don't know. Probably a long time.

I've already assigned myself to review some much older, bigger and higher priority PRs, and currently have no time review them. And there is quite a few of other PRs waiting in line. So I wouldn't count on me doing the review this year. It wouldn't be much of a quality review anyway, because as I said, we don't know Russian.

I can't really speak for others, but the rest of the team seems to have the same or even less amount of time, so I wouldn't count on them too.

Your best chance are external contributors who know Russian. I'd say one or two external reviews would be enough for us as an indicator that we can trust the PR and that the quality of the translation is sufficient so we can merge it.

**Review by Z128A — APPROVED** [review]
Great work!

**Comment by X64E** [comment]
If I understood correctly, commit had to be done from X64E:dev? Well, in principle, this is certainly a problem, but not a critical one. Because only the necessary files will be added anyway.

**Comment by X64E** [comment]
If i change X64E:master to X64E:dev . You merge this pull?

**Pull request closed without merging**
