### PR TITLE
Improve object.txt and update translations

### PR DESCRIPTION
**Pull request by hexagonrecursion**

### CODE REVIEW

**Review by tomaszkax86 — APPROVED** [review]

**Comment by nextghost** [comment]
@hexagonrecursion Please don't use machine translation. All you're doing is hiding untranslated strings from people who can translate them properly.

**Comment by hexagonrecursion** [comment]
@nextghost "Please don't use machine translation"

I added machine translation because @AndreiCherniaev [told me in a different pull request](https://github.com/colobot/colobot-data/pull/89#issuecomment-1923017381) "Please add others (sic) languages using auto translation!"

@tomaszkax86 What is the official policy? Should I add machine translation in future pull requests

**Comment by tomaszkax86** [comment]
@hexagonrecursion We don't have an official policy yet but we'll likely form one soon-ish, as well as a policy on AI generated content since it's starting to become an issue.

The main problem with machine translation is that without context you can't really form consistent translations. Sometimes you could get more formal text, other times you could get more casual text. Game-specific names can be translated in arbitrary way, like we use the term "bots" for robots, in other languages this can have multiple translations with slightly different meanings. If you don't know the target language you can't fix that, if machine translations are added then native speakers can be confused and have to assume that this is intentional for some reason.

As such, I think we'll no longer allow pure machine translations. If it's best to leave text untranslated than make a mess, then that's what we should do. Maybe we can allow it in specific cases, like for labels and buttons with short text, 1-3 words.

**Comment by tomangelo2** [comment]
Whenever I encounter machine translations it's hard to not notice they were made without any context. This makes me switch to an untranslated version, since machine translation only makes playing experience worse.

Poor human translation (*with an little amount of small errors*)\* are IMHO better than "correct" machine ones.

\*purposefully written as that, to point out you're still able to understand the general thought behind it.

**Comment by nextghost** [comment]
@hexagonrecursion At the very least, you need to set the [fuzzy flag](https://www.gnu.org/software/gettext/manual/html_node/Workflow-flags.html) on any machine translated strings so that translation tools highlight them for review.

**Pull request merged**
